services:
  - type: web
    name: flask-api
    runtime: docker
    dockerfilePath: Dockerfile.flask
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: streamlit-ui
    runtime: docker
    dockerfilePath: dockerfile.streamlit
    envVars:
      - key: PORT
        value: 8501